This notebook attempts to showcase the creation of a suitable list of largest mids (machine identifier) that are contained in both audio datasets Audioset and FSD50k. This list of mids is needed to produce a subset of needed segment files (less files needed means less conversions, I/O, and storage) and to produce accurate target labels for each file.

In [2]:
import pandas as pd
import utils.utility_funcs as my_utils

In [3]:
# Read in the metafiles of both fsd50k and audioset

# Change column names to be more cohesive with audioset
fsd50k_class_vocab = pd.read_csv(r'C:\Users\mp431591\Documents\FSD50k_label_files\vocabulary.csv',
                                 header=None, names=["display_name", "mids"])

fsd50k_mids = set(fsd50k_class_vocab["mids"])

# Same column name change as for fsd50k
audioset_mid_to_label_mapping = pd.read_csv(r'C:\Users\mp431591\Documents\audioset_label_files\mid_to_display_name.tsv',
                                     sep="\t", header=None, names=["mids", "display_name"])
audioset_mid_to_label_mapping.head()

            mids          display_name
0  /g/11b630rrvh        Kettle whistle
1    /g/122z_qxw           Firecracker
2      /m/01280g          Wild animals
3      /m/012f08  Motor vehicle (road)
4      /m/012n7d     Ambulance (siren)

In [4]:
# Read in audiosets strongly annotated training split meta file to quantify largest classes.
# While the evaluation splits information could also be used, the training split
# is larger and is most likely good enough.

# Audioset train labels
audioset_train_classes = pd.read_csv(r'C:\Users\mp431591\Documents\audioset_label_files\audioset_train_strong.tsv',
                                     sep="\t")
audioset_train_classes.head()

          segment_id  start_time_seconds  end_time_seconds       label
0  b0RFKhbpFJA_30000               0.000            10.000  /m/03m9d0z
1  b0RFKhbpFJA_30000               4.753             5.720   /m/05zppz
2  b0RFKhbpFJA_30000               0.000            10.000  /m/07pjwq1
3  b0RFKhbpFJA_30000               6.899             7.010  /m/07qjznt
4  b0RFKhbpFJA_30000               8.534             9.156  /t/dd00092

In [5]:
# Drop temporal information since we're aiming for weak labels
audioset_train_classes = audioset_train_classes.loc[:, ['segment_id', 'label']]
audioset_train_classes.head(5)

          segment_id       label
0  b0RFKhbpFJA_30000  /m/03m9d0z
1  b0RFKhbpFJA_30000   /m/05zppz
2  b0RFKhbpFJA_30000  /m/07pjwq1
3  b0RFKhbpFJA_30000  /m/07qjznt
4  b0RFKhbpFJA_30000  /t/dd00092

In [6]:
# Rename labels column to mids column for more accurate meaning and better coherence with FSD50k
audioset_train_classes.rename(columns={'label': 'mids'}, inplace=True)
audioset_train_classes.info()
# These steps are found in a utlity function as well

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 934821 entries, 0 to 934820
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   segment_id  934821 non-null  object
 1   mids        934821 non-null  object
dtypes: object(2)
memory usage: 14.3+ MB

In [7]:
# Drop duplicates in case any 10 sec clip has multiple instances of the same sound
# A quick manual look confirms these exist for at least audioset train
audioset_train_no_dups = audioset_train_classes.drop_duplicates()
audioset_train_no_dups.info()

<class 'pandas.core.frame.DataFrame'>
Index: 432296 entries, 0 to 934813
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   segment_id  432296 non-null  object
 1   mids        432296 non-null  object
dtypes: object(2)
memory usage: 9.9+ MB

In [8]:
# Drop rows where the mid is not found in the fsd50k mids.
rows_w_good_mid = audioset_train_no_dups.mids.isin(fsd50k_mids)
rows_w_good_mid
audioset_good_rows = audioset_train_no_dups[rows_w_good_mid]
audioset_good_rows.info()

<class 'pandas.core.frame.DataFrame'>
Index: 277487 entries, 0 to 934813
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   segment_id  277487 non-null  object
 1   mids        277487 non-null  object
dtypes: object(2)
memory usage: 6.4+ MB

In [9]:
# Count mid frequencies
audioset_train_labels_by_mid_count = (audioset_good_rows.value_counts() # add a value to unique rows (in practice should be 1)
                     .groupby(by='mids') # organize by mid
                     .sum() # Sum the mid specific value i.e, in how many segments does the mid appear
                     .sort_values(ascending=False))
audioset_train_labels_by_mid_count[0:50]

mids
/m/05zppz     35107
/m/04rlf      27135
/t/dd00077    26219
/m/07qjznt    18705
/m/0lyf6      16523
/m/02zsn      14240
/m/03m9d0z    10191
/m/09l8g       8997
/m/01h8n0      7282
/m/01j3sz      6846
/m/07qcpgn     5316
/m/020bb7      4838
/m/0ytgt       4247
/t/dd00003     4232
/m/07q2z82     3757
/m/07p6fty     3467
/m/07pbtc8     3261
/m/03qtwd      3022
/m/07pggtn     2774
/m/0838f       2706
/t/dd00004     2396
/m/09x0r       2341
/m/0l15bq      2225
/m/012f08      2189
/m/0k4j        1879
/m/07jdr       1675
/m/0jbk        1668
/m/05tny_      1636
/m/032s66      1288
/m/07qnq_y     1283
/m/053hz1      1179
/m/0bt9lr      1164
/m/0912c9      1028
/m/0395lw      1017
/m/0brhx       1001
/m/07r660_      986
/m/07rrlb6      958
/m/01b_21       942
/t/dd00112      941
/m/07s0dtb      895
/m/03qc9zr      842
/m/03vt0        824
/m/014zdl       822
/m/07r04        775
/m/028ght       773
/m/02rtxlg      753
/m/015lz1       727
/m/09xqv        716
/m/0btp2        701
/m/07pp_mv      699
Name: count, dtype: int64

In [32]:
# Get the top 50 - or any other subset - mids that can be used to narrow down the necessary files.
top_50_mids = audioset_train_labels_by_mid_count[0:50]
top_50_mids = set(top_50_mids.keys())

top_30_mids = audioset_train_labels_by_mid_count[0:30]
top_30_mids = set(top_30_mids.keys())

for idx, count in enumerate(audioset_train_labels_by_mid_count):
    #print(my_utils.audioset_mid_to_display_name(audioset_mid_to_label_mapping, mid))
    mid = audioset_train_labels_by_mid_count.index[idx]
    count = audioset_train_labels_by_mid_count.iloc[idx]
    readable_name = my_utils.audioset_mid_to_display_name(audioset_mid_to_label_mapping, mid)
    print(f"Label/mid: {readable_name} : {mid} and its count: {count}")

Label/mid: Male speech, man speaking : /m/05zppz and its count: 35107
Label/mid: Music : /m/04rlf and its count: 27135
Label/mid: Mechanisms : /t/dd00077 and its count: 26219
Label/mid: Tick : /m/07qjznt and its count: 18705
Label/mid: Breathing : /m/0lyf6 and its count: 16523
Label/mid: Female speech, woman speaking : /m/02zsn and its count: 14240
Label/mid: Wind : /m/03m9d0z and its count: 10191
Label/mid: Human voice : /m/09l8g and its count: 8997
Label/mid: Conversation : /m/01h8n0 and its count: 7282
Label/mid: Laughter : /m/01j3sz and its count: 6846
Label/mid: Tap : /m/07qcpgn and its count: 5316
Label/mid: Bird vocalization, bird call, bird song : /m/020bb7 and its count: 4838
Label/mid: Child speech, kid speaking : /m/0ytgt and its count: 4247
Label/mid: Male singing : /t/dd00003 and its count: 4232
Label/mid: Accelerating, revving, vroom : /m/07q2z82 and its count: 3757
Label/mid: Shout : /m/07p6fty and its count: 3467
Label/mid: Walk, footsteps : /m/07pbtc8 and its count: 3261
Label/mid: Crowd : /m/03qtwd and its count: 3022
Label/mid: Chirp, tweet : /m/07pggtn and its count: 2774
Label/mid: Water : /m/0838f and its count: 2706
Label/mid: Female singing : /t/dd00004 and its count: 2396
Label/mid: Speech : /m/09x0r and its count: 2341
Label/mid: Clapping : /m/0l15bq and its count: 2225
Label/mid: Motor vehicle (road) : /m/012f08 and its count: 2189
Label/mid: Car : /m/0k4j and its count: 1879
Label/mid: Train : /m/07jdr and its count: 1675
Label/mid: Animal : /m/0jbk and its count: 1668
Label/mid: Bark : /m/05tny_ and its count: 1636
Label/mid: Gunshot, gunfire : /m/032s66 and its count: 1288
Label/mid: Thump, thud : /m/07qnq_y and its count: 1283
Label/mid: Cheering : /m/053hz1 and its count: 1179
Label/mid: Dog : /m/0bt9lr and its count: 1164
Label/mid: Vehicle horn, car horn, honking, toot : /m/0912c9 and its count: 1028
Label/mid: Bell : /m/0395lw and its count: 1017
Label/mid: Speech synthesizer : /m/0brhx and its count: 1001
Label/mid: Giggle : /m/07r660_ and its count: 986
Label/mid: Splash, splatter : /m/07rrlb6 and its count: 958
Label/mid: Cough : /m/01b_21 and its count: 942
Label/mid: Crumpling, crinkling : /t/dd00112 and its count: 941
Label/mid: Gasp : /m/07s0dtb and its count: 895
Label/mid: Screaming : /m/03qc9zr and its count: 842
Label/mid: Insect : /m/03vt0 and its count: 824
Label/mid: Explosion : /m/014zdl and its count: 822
Label/mid: Truck : /m/07r04 and its count: 775
Label/mid: Applause : /m/028ght and its count: 773
Label/mid: Whispering : /m/02rtxlg and its count: 753
Label/mid: Singing : /m/015lz1 and its count: 727
Label/mid: Cricket : /m/09xqv and its count: 716
Label/mid: Traffic noise, roadway noise : /m/0btp2 and its count: 701
Label/mid: Alarm : /m/07pp_mv and its count: 699
Label/mid: Run : /m/06h7j and its count: 676
Label/mid: Growling : /m/0ghcn6 and its count: 659
Label/mid: Waves, surf : /m/034srq and its count: 655
Label/mid: Engine : /m/02mk9 and its count: 649
Label/mid: Siren : /m/03kmc9 and its count: 645
Label/mid: Motorcycle : /m/04_sv and its count: 626
Label/mid: Vehicle : /m/07yv9 and its count: 576
Label/mid: Chicken, rooster : /m/09b5t and its count: 566
Label/mid: Dishes, pots, and pans : /m/04brg2 and its count: 558
Label/mid: Stream, river : /m/0j6m2 and its count: 541
Label/mid: Water tap, faucet : /m/02jz0l and its count: 536
Label/mid: Computer keyboard : /m/01m2v and its count: 530
Label/mid: Crying, sobbing : /m/0463cq4 and its count: 524
Label/mid: Engine starting : /t/dd00130 and its count: 519
Label/mid: Fire : /m/02_41 and its count: 514
Label/mid: Rain : /m/06mb1 and its count: 501
Label/mid: Race car, auto racing : /m/0ltv and its count: 485
Label/mid: Trickle, dribble : /m/07pqc89 and its count: 480
Label/mid: Chewing, mastication : /m/03cczk and its count: 473
Label/mid: Pour : /m/07prgkl and its count: 457
Label/mid: Buzz : /m/07pjwq1 and its count: 451
Label/mid: Glass shatter : /m/07rn7sz and its count: 447
Label/mid: Cat : /m/01yrx and its count: 444
Label/mid: Door : /m/02dgv and its count: 385
Label/mid: Hammer : /m/03l9g and its count: 383
Label/mid: Burping, eructation : /m/03q5_w and its count: 381
Label/mid: Power tool : /m/0_ksk and its count: 379
Label/mid: Skateboard : /m/06_fw and its count: 374
Label/mid: Glass chink, clink : /m/07q7njn and its count: 372
Label/mid: Bird : /m/015p6 and its count: 365
Label/mid: Drill : /m/01d380 and its count: 356
Label/mid: Bus : /m/01bjv and its count: 355
Label/mid: Meow : /m/07qrkrw and its count: 353
Label/mid: Drip : /m/07r5v4s and its count: 350
Label/mid: Church bell : /m/03w41f and its count: 349
Label/mid: Squeak : /m/07q6cd_ and its count: 347
Label/mid: Aircraft : /m/0k5j and its count: 344
Label/mid: Liquid : /m/04k94 and its count: 338
Label/mid: Subway, metro, underground : /m/0195fx and its count: 336
Label/mid: Toilet flush : /m/01jt3m and its count: 333
Label/mid: Sneeze : /m/01hsr_ and its count: 331
Label/mid: Boat, Water vehicle : /m/019jd and its count: 329
Label/mid: Cutlery, silverware : /m/023pjk and its count: 323
Label/mid: Mechanical fan : /m/02x984l and its count: 320
Label/mid: Writing : /m/081rb and its count: 317
Label/mid: Car passing by : /t/dd00134 and its count: 317
Label/mid: Ocean : /m/05kq4 and its count: 316
Label/mid: Rattle : /m/07qn4z3 and its count: 315
Label/mid: Slam : /m/07rjzl8 and its count: 311
Label/mid: Printer : /m/01m4t and its count: 306
Label/mid: Fart : /m/02_nn and its count: 303
Label/mid: Ringtone : /m/01hnzm and its count: 296
Label/mid: Camera : /m/0dv5r and its count: 294
Label/mid: Whoosh, swoosh, swish : /m/07rqsjt and its count: 290
Label/mid: Thunder : /m/0ngt1 and its count: 286
Label/mid: Frog : /m/09ld4 and its count: 281
Label/mid: Hiss : /m/07rjwbb and its count: 276
Label/mid: Bicycle, tricycle : /m/0199g and its count: 268
Label/mid: Frying (food) : /m/0dxrf and its count: 266
Label/mid: Fireworks : /m/0g6b5 and its count: 261
Label/mid: Thunderstorm : /m/0jb2l and its count: 251
Label/mid: Purr : /m/02yds9 and its count: 250
Label/mid: Sliding door : /m/02y_763 and its count: 246
Label/mid: Fixed-wing aircraft, airplane : /m/0cmf2 and its count: 239
Label/mid: Chuckle, chortle : /m/07rgt08 and its count: 238
Label/mid: Sink (filling or washing) : /m/0130jx and its count: 233
Label/mid: Gurgling, bubbling : /m/07swgks and its count: 231
Label/mid: Coin (dropping) : /m/0242l and its count: 228
Label/mid: Glass : /m/039jq and its count: 226
Label/mid: Doorbell : /m/03wwcy and its count: 226
Label/mid: Idling : /m/07pb8fc and its count: 224
Label/mid: Ratchet, pawl : /m/02bm9n and its count: 222
Label/mid: Tools : /m/07k1x and its count: 210
Label/mid: Finger snapping : /m/025_jnm and its count: 209
Label/mid: Boiling : /m/0dv3j and its count: 205
Label/mid: Wind chime : /m/026fgl and its count: 205
Label/mid: Typewriter : /m/0c2wf and its count: 196
Label/mid: Tick-tock : /m/07qjznl and its count: 196
Label/mid: Hands : /m/0k65p and its count: 195
Label/mid: Keys jangling : /m/03v3yw and its count: 192
Label/mid: Cowbell : /m/0239kh and its count: 186
Label/mid: Sigh : /m/07plz5l and its count: 182
Label/mid: Crow : /m/04s8yn and its count: 180
Label/mid: Zipper (clothing) : /m/01s0vc and its count: 175
Label/mid: Scissors : /m/01lsmm and its count: 173
Label/mid: Sawing : /m/01b82r and its count: 168
Label/mid: Microwave oven : /m/0fx9l and its count: 160
Label/mid: Tearing : /m/07qcx4z and its count: 153
Label/mid: Bicycle bell : /m/0gy1t2s and its count: 144
Label/mid: Bathtub (filling or washing) : /m/03dnzn and its count: 144
Label/mid: Clock : /m/01x3z and its count: 143
Label/mid: Fill (with liquid) : /m/07p7b8y and its count: 143
Label/mid: Typing : /m/0316dw and its count: 138
Label/mid: Knock : /m/07r4wb8 and its count: 133
Label/mid: Drawer open or close : /m/0fqfqc and its count: 133
Label/mid: Crackle : /m/07pzfmf and its count: 123
Label/mid: Rail transport : /m/06d_3 and its count: 120
Label/mid: Crushing : /m/07plct2 and its count: 101
Label/mid: Wood : /m/083vt and its count: 89
Label/mid: Wild animals : /m/01280g and its count: 80
Label/mid: Chime : /m/0f8s22 and its count: 74
Label/mid: Fowl : /m/025rv6n and its count: 52
Label/mid: Telephone : /m/07cx4 and its count: 47
Label/mid: Crack : /m/07qs1cx and its count: 45
Label/mid: Boom : /m/07qqyl4 and its count: 43
Label/mid: Yell : /m/07sr1lc and its count: 33
Label/mid: Cupboard open or close : /m/0642b4 and its count: 29
Label/mid: Domestic animals, pets : /m/068hy and its count: 14
Label/mid: Raindrop : /m/07r10fb and its count: 14
Label/mid: Packing tape, duct tape : /m/05mxj0q and its count: 13
Label/mid: Gull, seagull : /m/01dwxx and its count: 8
Label/mid: Human group actions : /t/dd00012 and its count: 8
Label/mid: Screech : /m/07q8k13 and its count: 4
Label/mid: Respiratory sounds : /m/09hlz4 and its count: 4
Label/mid: Livestock, farm animals, working animals : /m/0ch8v and its count: 3

In [28]:
audioset_train_labels_by_mid_count.index[0]

'/m/05zppz'

In [ ]:
# Save the object as a pickle object for further downstream use.
from utils.utility_funcs import pickle_save
pickle_save("mid_objects/top_50_mids.pckl", top_50_mids)

In [ ]:
pickle_save("mid_objects/top_30_mids.pckl", top_30_mids)