This notebook is used to get the appropriate audio file names from Audioset's and FSD50k's training and evaluation sets that correspond to a given mid (Machine identifier) list. This list of filenames can then be used to construct appropriate dataset specific training and evaluation sets for further downstream machine learning. Corresponding label files can also be constructed.

In [17]:
import os
import zipfile as zf

import pandas as pd

import utils.utility_funcs as my_util

In [18]:


# Load in the respective metafiles for both audioset and fsd50k, keeping only relevant columns
PATH_TO_AS_TRAIN = r'C:\Users\mp431591\Documents\audioset_label_files\audioset_train_strong.tsv'
PATH_TO_AS_EVAL = r'C:\Users\mp431591\Documents\audioset_label_files\audioset_eval_strong.tsv'

PATH_TO_FSD_TRAIN = r'C:\Users\mp431591\Documents\FSD50k_label_files\dev.csv' # dev == train
PATH_TO_FSD_EVAL = r'C:\Users\mp431591\Documents\FSD50k_label_files\eval.csv'

audioset_train_meta = my_util.read_strong_audioset_metatable(PATH_TO_AS_TRAIN)
audioset_eval_meta = my_util.read_strong_audioset_metatable(PATH_TO_AS_EVAL)

fsd50k_train_meta = my_util.read_fsd50k_metatable(PATH_TO_FSD_TRAIN)
fsd50k_eval_meta = my_util.read_fsd50k_metatable(PATH_TO_FSD_EVAL)

audioset_eval_meta.head()

          segment_id       mids
0  s9d-2nhuJCQ_30000   /m/04rlf
1  s9d-2nhuJCQ_30000  /m/053hz1
2  s9d-2nhuJCQ_30000  /m/03qtwd
3  s9d-2nhuJCQ_30000  /m/01w250
4  s9d-2nhuJCQ_30000  /m/0l15bq

In [19]:
fsd50k_train_meta.head()

   fname                                           mids
0  64760  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
1  16399  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
2  16401  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
3  16402  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf
4  16404  /m/02sgy,/m/0342h,/m/0fx80y,/m/04szw,/m/04rlf

In [20]:
# Explode the fsd50k table to make checking for valid rows easier
# Also conforms to the form of the Audioset data -> operations can be similar
# across datasets
fsd50k_train_meta_exploded = (fsd50k_train_meta.set_index(["fname"])
                              .apply(lambda x: x.str.split(',')
                                     .explode())
                                     .reset_index())
fsd50k_train_meta_exploded.head(10)

   fname       mids
0  64760   /m/02sgy
1  64760   /m/0342h
2  64760  /m/0fx80y
3  64760   /m/04szw
4  64760   /m/04rlf
5  16399   /m/02sgy
6  16399   /m/0342h
7  16399  /m/0fx80y
8  16399   /m/04szw
9  16399   /m/04rlf

In [21]:
fsd50k_eval_meta_exploded = (fsd50k_eval_meta.set_index(["fname"])
                              .apply(lambda x: x.str.split(',')
                                     .explode())
                                     .reset_index())
fsd50k_eval_meta_exploded.head(10)

    fname       mids
0   37199   /m/02sgy
1   37199   /m/0342h
2   37199  /m/0fx80y
3   37199   /m/04szw
4   37199   /m/04rlf
5  175151   /m/02sgy
6  175151   /m/0342h
7  175151  /m/0fx80y
8  175151   /m/04szw
9  175151   /m/04rlf

In [22]:
meta_tables = {"audioset_train_meta": audioset_train_meta,
               "audioset_eval_meta": audioset_eval_meta,
               "fsd50k_train_meta_exploded": fsd50k_train_meta_exploded,
               "fsd50k_eval_meta_exploded": fsd50k_eval_meta_exploded}

In [23]:
PATH_TO_MIDS_BY_AS_COUNT = r'C:\Users\mp431591\Documents\work_code\cl_30\continual_learning\pickle_objects\mids_by_AStrain_counts.pckl'

# Load a mid to display name vocabulary as well
PATH_TO_AS_VOCAB = r'C:\Users\mp431591\Documents\audioset_label_files\mid_to_display_name.tsv'
audioset_mid_to_label_mapping = pd.read_csv(PATH_TO_AS_VOCAB,
                                     sep="\t", header=None, names=["mids", "display_name"])
# Make a copy to retain original table and refine the copy to a dict
as_mid_to_label_map_copy = audioset_mid_to_label_mapping.set_index('mids')
as_mid_to_display_dict = as_mid_to_label_map_copy.to_dict()['display_name']
as_mid_to_display_dict

{'/g/11b630rrvh': 'Kettle whistle',
 '/g/122z_qxw': 'Firecracker',
 '/m/01280g': 'Wild animals',
 '/m/012f08': 'Motor vehicle (road)',
 '/m/012n7d': 'Ambulance (siren)',
 '/m/012ndj': 'Fire engine, fire truck (siren)',
 '/m/012xff': 'Toothbrush',
 '/m/0130jx': 'Sink (filling or washing)',
 '/m/014yck': 'Aircraft engine',
 '/m/014zdl': 'Explosion',
 '/m/0150b9': 'Change ringing (campanology)',
 '/m/015jpf': 'Dial tone',
 '/m/015lz1': 'Singing',
 '/m/015p6': 'Bird',
 '/m/0160x5': 'Digestive',
 '/m/0174k2': 'Washing machine',
 '/m/018p4k': 'Cart',
 '/m/018w8': 'Basketball bounce',
 '/m/0193bn': 'Sonic boom',
 '/m/0195fx': 'Subway, metro, underground',
 '/m/0199g': 'Bicycle, tricycle',
 '/m/019jd': 'Boat, Water vehicle',
 '/m/01b82r': 'Sawing',
 '/m/01b9nn': 'Reverberation',
 '/m/01b_21': 'Cough',
 '/m/01bjv': 'Bus',
 '/m/01c194': 'Mantra',
 '/m/01d380': 'Drill',
 '/m/01d3sd': 'Snoring',
 '/m/01dwxx': 'Gull, seagull',
 '/m/01g50p': 'Railroad car, train wagon',
 '/m/01g90h': 'Stomach rumble',
 '/m/01h3n': 'Bee, wasp, etc.',
 '/m/01h82_': 'Engine knocking',
 '/m/01h8n0': 'Conversation',
 '/m/01hhp3': 'Yak',
 '/m/01hnzm': 'Ringtone',
 '/m/01hsr_': 'Sneeze',
 '/m/01j2bj': 'Bathroom sounds',
 '/m/01j3j8': 'Studio recording',
 '/m/01j3sz': 'Laughter',
 '/m/01j423': 'Yawn',
 '/m/01j4z9': 'Chainsaw',
 '/m/01jg02': 'Heart sounds, heartbeat',
 '/m/01jg1z': 'Heart murmur',
 '/m/01jnbd': 'Echo',
 '/m/01jt3m': 'Toilet flush',
 '/m/01jwx6': 'Vibration',
 '/m/01lsmm': 'Scissors',
 '/m/01lynh': 'Stairs',
 '/m/01m2v': 'Computer keyboard',
 '/m/01m4t': 'Printer',
 '/m/01rd7k': 'Turkey',
 '/m/01s0vc': 'Zipper (clothing)',
 '/m/01sb50': 'Cellphone buzz, vibrating alert',
 '/m/01swy6': 'Yodeling',
 '/m/01v_m0': 'Sine wave',
 '/m/01w250': 'Whistling',
 '/m/01x3z': 'Clock',
 '/m/01xq0k1': 'Cattle, bovinae',
 '/m/01y3hg': 'Smoke detector, smoke alarm',
 '/m/01yg9g': 'Lawn mower',
 '/m/01yrx': 'Cat',
 '/m/01z47d': 'Busy signal',
 '/m/01z5f': 'Canidae, wild dogs, wolves',
 '/m/02021': 'Chipmunk',
 '/m/020bb7': 'Bird vocalization, bird call, bird song',
 '/m/0239kh': 'Cowbell',
 '/m/023pjk': 'Cutlery, silverware',
 '/m/023vsd': 'Sanding',
 '/m/02417f': 'Windscreen wiper, windshield wiper',
 '/m/0242l': 'Coin (dropping)',
 '/m/024dl': 'Cash register',
 '/m/025_jnm': 'Finger snapping',
 '/m/025rv6n': 'Fowl',
 '/m/025wky1': 'Air conditioning',
 '/m/0261r1': 'Babbling',
 '/m/0269r2s': 'Chain',
 '/m/026fgl': 'Wind chime',
 '/m/027m70_': 'Jingle bell',
 '/m/0284vy3': 'Train horn',
 '/m/028ght': 'Applause',
 '/m/028v0c': 'Silence',
 '/m/02_41': 'Fire',
 '/m/02_nn': 'Fart',
 '/m/02bk07': 'Chant',
 '/m/02bm9n': 'Ratchet, pawl',
 '/m/02c8p': 'Telephone dialing, DTMF',
 '/m/02dgv': 'Door',
 '/m/02f9f_': 'Shower',
 '/m/02fs_r': 'Beep, bleep',
 '/m/02fxyj': 'Humming',
 '/m/02g901': 'Electric shaver, electric razor',
 '/m/02jz0l': 'Water tap, faucet',
 '/m/02l6bg': 'Propeller, airscrew',
 '/m/02ll1_': 'Lock',
 '/m/02mfyn': 'Car alarm',
 '/m/02mk9': 'Engine',
 '/m/02p01q': 'Filing (rasp)',
 '/m/02p3nc': 'Hiccup',
 '/m/02pjr4': 'Blender, food processor',
 '/m/02qldy': 'Narration, monologue',
 '/m/02rhddq': 'Reversing beeps',
 '/m/02rlv9': 'Motorboat, speedboat',
 '/m/02rr_': 'Effects unit',
 '/m/02rtxlg': 'Whispering',
 '/m/02x984l': 'Mechanical fan',
 '/m/02y_763': 'Sliding door',
 '/m/02yds9': 'Purr',
 '/m/02z32qm': 'Fusillade',
 '/m/02zsn': 'Female speech, woman speaking',
 '/m/030rvx': 'Buzzer',
 '/m/0316dw': 'Typing',
 '/m/032n05': 'Whale vocalization',
 '/m/032s66': 'Gunshot, gunfire',
 '/m/034srq': 'Waves, surf',
 '/m/0395lw': 'Bell',
 '/m/039jq': 'Glass',
 '/m/03cczk': 'Chewing, mastication',
 '/m/03cl9h': 'Ice cream truck, ice cream van',
 '/m/03dnzn': 'Bathtub (filling or washing)',
 '/m/03fwl': 'Goat',
 '/m/03j1ly': 'Emergency vehicle',
 '/m/03k3r': 'Horse',
 '/m/03kmc9': 'Siren',
 '/m/03l9g': 'Hammer',
 '/m/03m9d0z': 'Wind',
 '/m/03p19w': 'Jackhammer',
 '/m/03q5_w': 'Burping, eructation',
 '/m/03qc9zr': 'Screaming',
 '/m/03qtwd': 'Crowd',
 '/m/03v3yw': 'Keys jangling',
 '/m/03vt0': 'Insect',
 '/m/03w41f': 'Church bell',
 '/m/03wvsk': 'Hair dryer',
 '/m/03wwcy': 'Doorbell',
 '/m/040b_t': 'Refrigerator',
 '/m/04179zz': 'Duck call (hunting tool)',
 '/m/04229': 'Jet engine',
 '/m/0463cq4': 'Crying, sobbing',
 '/m/046dlr': 'Alarm clock',
 '/m/04_sv': 'Motorcycle',
 '/m/04brg2': 'Dishes, pots, and pans',
 '/m/04ctx': 'Knife',
 '/m/04cvmfc': 'Roar',
 '/m/04fgwm': 'Electric toothbrush',
 '/m/04fq5q': 'Foghorn',
 '/m/04gxbd': 'Power windows, electric windows',
 '/m/04gy_2': 'Battle cry',
 '/m/04k94': 'Liquid',
 '/m/04qvtq': 'Police car (siren)',
 '/m/04rlf': 'Music',
 '/m/04rmv': 'Mouse',
 '/m/04s8yn': 'Crow',
 '/m/04v5dt': 'Booing',
 '/m/04zjc': 'Machine gun',
 '/m/04zmvq': 'Train whistle',
 '/m/053hz1': 'Cheering',
 '/m/056ks2': 'Rowboat, canoe, kayak',
 '/m/056r_1': 'Keypress tone',
 '/m/05_wcq': 'Bird flight, flapping wings',
 '/m/05kq4': 'Ocean',
 '/m/05mxj0q': 'Packing tape, duct tape',
 '/m/05rj2': 'Shuffling cards',
 '/m/05tny_': 'Bark',
 '/m/05x_td': 'Air horn, truck horn',
 '/m/05zc1': 'Pulleys',
 '/m/05zppz': 'Male speech, man speaking',
 '/m/0641k': 'Paper rustling',
 '/m/0642b4': 'Cupboard open or close',
 '/m/068hy': 'Domestic animals, pets',
 '/m/068zj': 'Pig',
 '/m/06_fw': 'Skateboard',
 '/m/06_y0by': 'Environmental noise',
 '/m/06bxc': 'Rapping',
 '/m/06bz3': 'Radio',
 '/m/06cyt0': 'Mechanical bell',
 '/m/06d_3': 'Rail transport',
 '/m/06h7j': 'Run',
 '/m/06hck5': 'Steam whistle',
 '/m/06hps': 'Rodents, rats, mice',
 '/m/06mb1': 'Rain',
 '/m/06q74': 'Ship',
 '/m/06wzb': 'Steam',
 '/m/06xkwv': 'Mains hum',
 '/m/073cg4': 'Cap gun',
 '/m/078jl': 'Snake',
 '/m/0790c': 'Sonar',
 '/m/079vc8': 'Wolf-whistling',
 '/m/07bgp': 'Sheep',
 '/m/07bjf': 'Single-lens reflex camera',
 '/m/07bm98': 'Sound reproduction',
 '/m/07c52': 'Television',
 '/m/07cx4': 'Telephone',
 '/m/07hvw1': 'Unmodified field recording',
 '/m/07jdr': 'Train',
 '/m/07k1x': 'Tools',
 '/m/07m2kt': 'Chorus effect',
 '/m/07mzm6': 'Wheeze',
 '/m/07n_g': 'Tuning fork',
 '/m/07p6fty': 'Shout',
 '/m/07p6mqd': 'Slosh',
 '/m/07p78v5': 'Zing',
 '/m/07p7b8y': 'Fill (with liquid)',
 '/m/07p9k1k': 'Sizzle',
 '/m/07p_0gm': 'Throbbing',
 '/m/07pb8fc': 'Idling',
 '/m/07pbtc8': 'Walk, footsteps',
 '/m/07pc8l3': 'Snap',
 '/m/07pc8lb': 'Breaking',
 '/m/07pczhz': 'Chop',
 '/m/07pdhp0': 'Biting',
 '/m/07pdjhy': 'Rub',
 '/m/07pggtn': 'Chirp, tweet',
 '/m/07phhsh': 'Rumble',
 '/m/07phxs1': 'Ding',
 '/m/07pjjrj': 'Smash, crash',
 '/m/07pjwq1': 'Buzz',
 '/m/07pk7mg': 'Wobble',
 '/m/07pl1bw': 'Splinter',
 '/m/07plct2': 'Crushing',
 '/m/07plz5l': 'Sigh',
 '/m/07pn_8q': 'Chopping (food)',
 '/m/07pp8cl': 'Telephone bell ringing',
 '/m/07pp_mv': 'Alarm',
 '/m/07ppn3j': 'Sniff',
 '/m/07pqc89': 'Trickle, dribble',
 '/m/07pqmly': 'Slurp, drinking straw',
 '/m/07pqn27': 'Bouncing',
 '/m/07prgkl': 'Pour',
 '/m/07pt6mm': 'Grind',
 '/m/07pt_g0': 'Pulse',
 '/m/07ptfmf': 'Stir',
 '/m/07ptzwd': 'Pump (liquid)',
 '/m/07pws3f': 'Bang',
 '/m/07pxg6y': 'Eruption',
 '/m/07pyf11': 'Flap',
 '/m/07pyy8b': 'Pant',
 '/m/07pzfmf': 'Crackle',
 '/m/07q0h5t': 'Bleat',
 '/m/07q0yl5': 'Snort',
 '/m/07q2z82': 'Accelerating, revving, vroom',
 '/m/07q34h3': 'Puff',
 '/m/07q4ntr': 'Bellow',
 '/m/07q5rw0': 'Neigh, whinny',
 '/m/07q6cd_': 'Squeak',
 '/m/07q7njn': 'Glass chink, clink',
 '/m/07q8f3b': 'Howl (wind)',
 '/m/07q8k13': 'Screech',
 '/m/07qb_dv': 'Scratch',
 '/m/07qc9xj': 'Clicking',
 '/m/07qcpgn': 'Tap',
 '/m/07qcx4z': 'Tearing',
 '/m/07qdb04': 'Quack',
 '/m/07qf0zm': 'Howl',
 '/m/07qfgpx': 'Jingle, tinkle',
 '/m/07qfr4h': 'Hubbub, speech noise, speech babble',
 '/m/07qh7jl': 'Creak',
 '/m/07qjznl': 'Tick-tock',
 '/m/07qjznt': 'Tick',
 '/m/07qlf79': 'Spray',
 '/m/07qlwh6': 'Squish',
 '/m/07qmpdm': 'Clatter',
 '/m/07qn4z3': 'Rattle',
 '/m/07qn5dc': 'Crowing, cock-a-doodle-doo',
 '/m/07qnq_y': 'Thump, thud',
 '/m/07qqyl4': 'Boom',
 '/m/07qrkrw': 'Meow',
 '/m/07qs1cx': 'Crack',
 '/m/07qsvvw': 'Burst, pop',
 '/m/07qv4k0': 'Scrape',
 '/m/07qv_x_': 'Shuffle',
 '/m/07qw_06': 'Wail, moan',
 '/m/07qwdck': 'Ping',
 '/m/07qwf61': 'Honk',
 '/m/07qwyj0': 'Rustle',
 '/m/07qyrcz': 'Plop',
 '/m/07qz6j3': 'Whimper',
 '/m/07r04': 'Truck',
 '/m/07r10fb': 'Raindrop',
 '/m/07r4gkf': 'Patter',
 '/m/07r4k75': 'Grunt',
 '/m/07r4wb8': 'Knock',
 '/m/07r5c2p': 'Caw',
 '/m/07r5v4s': 'Drip',
 '/m/07r660_': 'Giggle',
 '/m/07r67yg': 'Ding-dong',
 '/m/07r81j2': 'Caterwaul',
 '/m/07r_25d': 'Coo',
 '/m/07r_80w': 'Hoot',
 '/m/07r_k2n': 'Yip',
 '/m/07rbp7_': 'Whip',
 '/m/07rc7d9': 'Bow-wow',
 '/m/07rcgpl': 'Hum',
 '/m/07rdhzs': 'Whack, thwack',
 '/m/07rgkc5': 'Static',
 '/m/07rgt08': 'Chuckle, chortle',
 '/m/07rjwbb': 'Hiss',
 '/m/07rjzl8': 'Slam',
 '/m/07rn7sz': 'Glass shatter',
 '/m/07rpkh9': 'Moo',
 '/m/07rqsjt': 'Whoosh, swoosh, swish',
 '/m/07rrh0c': 'Thunk',
 '/m/07rrlb6': 'Splash, splatter',
 '/m/07rv4dm': 'Clang',
 '/m/07rv9rh': 'Clip-clop',
 '/m/07rwj3x': 'Whoop',
 '/m/07rwm0c': 'Clickety-clack',
 '/m/07ryjzk': 'Slap, smack',
 '/m/07s02z0': 'Squeal',
 '/m/07s04w4': 'Snicker',
 '/m/07s0dtb': 'Gasp',
 '/m/07s12q4': 'Crunch',
 '/m/07s13rg': 'Sweeping',
 '/m/07s2xch': 'Groan',
 '/m/07s34ls': 'Whir',
 '/m/07s8j8t': 'Roll',
 '/m/07sk0jz': 'Stomp, stamp',
 '/m/07sq110': 'Belly laugh',
 '/m/07sr1lc': 'Yell',
 '/m/07st88b': 'Croak',
 '/m/07st89h': 'Cluck',
 '/m/07svc2k': 'Gobble',
 '/m/07swgks': 'Gurgling, bubbling',
 '/m/07sx8x_': 'Squawk',
 '/m/07szfh9': 'Cacophony',
 '/m/07yv9': 'Vehicle',
 '/m/081rb': 'Writing',
 '/m/0838f': 'Water',
 '/m/083vt': 'Wood',
 '/m/08dckq': 'Carbon monoxide detector, CO detector',
 '/m/08j51y': "Dental drill, dentist's drill",
 '/m/0912c9': 'Vehicle horn, car horn, honking, toot',
 '/m/0939n_': 'Gargling',
 '/m/093_4n': 'Background noise',
 '/m/096m7z': 'Noise',
 '/m/098_xr': 'Error signal',
 '/m/09b5t': 'Chicken, rooster',
 '/m/09ct_': 'Helicopter',
 '/m/09d1b1': 'Tape hiss',
 '/m/09d5_': 'Owl',
 '/m/09ddx': 'Ducks, geese, waterfowl',
 '/m/09f96': 'Mosquito',
 '/m/09hlz4': 'Respiratory sounds',
 '/m/09l8g': 'Human voice',
 '/m/09ld4': 'Frog',
 '/m/09x0r': 'Speech',
 '/m/09xqv': 'Cricket',
 '/m/0_1c': 'Artillery fire',
 '/m/0_ksk': 'Power tool',
 '/m/0b_fwt': 'Electronic tuner',
 '/m/0bcdqg': 'Ringing tone, ringback tone',
 '/m/0bpl036': 'Human locomotion',
 '/m/0brhx': 'Speech synthesizer',
 '/m/0bt9lr': 'Dog',
 '/m/0btp2': 'Traffic noise, roadway noise',
 '/m/0bzvm2': 'Video game sound',
 '/m/0c1dj': 'Sound effect',
 '/m/0c1tlg': 'Electric rotor drone, quadcopter',
 '/m/0c2wf': 'Typewriter',
 '/m/0c3f7m': 'Fire alarm',
 '/m/0cdnk': 'Roaring cats (lions, tigers)',
 '/m/0ch8v': 'Livestock, farm animals, working animals',
 '/m/0chx_': 'White noise, pink noise',
 '/m/0cmf2': 'Fixed-wing aircraft, airplane',
 '/m/0d31p': 'Vacuum cleaner',
 '/m/0d4wf': 'Kitchen and dining room sounds',
 '/m/0dgbq': 'Civil defense siren',
 '/m/0dgw9r': 'Human sounds',
 '/m/0dl83': 'Arrow',
 '/m/0dl9sf8': 'Throat clearing',
 '/m/0dv3j': 'Boiling',
 '/m/0dv5r': 'Camera',
 '/m/0dxrf': 'Frying (food)',
 '/m/0f8s22': 'Chime',
 '/m/0ffhf': 'Donkey, ass',
 '/m/0fjy1': 'Wildfire',
 '/m/0fqfqc': 'Drawer open or close',
 '/m/0fw86': 'Tap dance',
 '/m/0fx9l': 'Microwave oven',
 '/m/0g12c5': 'Distortion',
 '/m/0g6b5': 'Fireworks',
 '/m/0ghcn6': 'Growling',
 '/m/0gvgw0': 'Air brake',
 '/m/0gy1t2s': 'Bicycle bell',
 '/m/0h0rv': 'Pigeon, dove',
 '/m/0h2mp': 'Fly, housefly',
 '/m/0h9mv': 'Tire squeal, skidding',
 '/m/0hdsk': 'Chirp tone',
 '/m/0hg7b': 'Microphone',
 '/m/0hgq8df': 'Crockery breaking and smashing',
 '/m/0hsrw': 'Sailboat, sailing ship',
 '/m/0j2kx': 'Waterfall',
 '/m/0j6m2': 'Stream, river',
 '/m/0jb2l': 'Thunderstorm',
 '/m/0jbk': 'Animal',
 '/m/0k4j': 'Car',
 '/m/0k5j': 'Aircraft',
 '/m/0k65p': 'Hands',
 '/m/0l14jd': 'Choir',
 '/m/0l156k': 'Whistle',
 '/m/0l15bq': 'Clapping',
 '/m/0l7xg': 'Gears',
 '/m/0llzx': 'Sewing machine',
 '/m/0ltv': 'Race car, auto racing',
 '/m/0lyf6': 'Breathing',
 '/m/0md09': 'Power saw, circular saw, table saw',
 '/m/0ngt1': 'Thunder',
 '/m/0ytgt': 'Child speech, kid speaking',
 '/m/0zmy2j9': 'Velcro, hook and loop fastener',
 '/t/dd00001': 'Baby laughter',
 '/t/dd00002': 'Baby cry, infant cry',
 '/t/dd00003': 'Male singing',
 '/t/dd00004': 'Female singing',
 '/t/dd00005': 'Child singing',
 '/t/dd00006': 'Synthetic singing',
 '/t/dd00012': 'Human group actions',
 '/t/dd00013': 'Children playing',
 '/t/dd00018': 'Oink',
 '/t/dd00038': 'Rain on surface',
 '/t/dd00048': 'Train wheels squealing',
 '/t/dd00061': 'Non-motorized land vehicle',
 '/t/dd00065': 'Light engine (high frequency)',
 '/t/dd00066': 'Medium engine (mid frequency)',
 '/t/dd00067': 'Heavy engine (low frequency)',
 '/t/dd00077': 'Mechanisms',
 '/t/dd00088': 'Gush',
 '/t/dd00091': 'Sound equipment',
 '/t/dd00092': 'Wind noise (microphone)',
 '/t/dd00098': 'Source-ambiguous sounds',
 '/t/dd00099': 'Generic impact sounds',
 '/t/dd00108': 'Clunk',
 '/t/dd00109': 'Surface contact',
 '/t/dd00110': 'Deformable shell',
 '/t/dd00112': 'Crumpling, crinkling',
 '/t/dd00118': 'Fizz',
 '/t/dd00121': 'Boing',
 '/t/dd00122': 'Other sourceless',
 '/t/dd00123': 'Channel, environment and background',
 '/t/dd00125': 'Inside, small room',
 '/t/dd00126': 'Inside, large room or hall',
 '/t/dd00127': 'Inside, public space',
 '/t/dd00128': 'Outside, urban or manmade',
 '/t/dd00129': 'Outside, rural or natural',
 '/t/dd00130': 'Engine starting',
 '/t/dd00133': 'Specific impact sounds',
 '/t/dd00134': 'Car passing by',
 '/t/dd00135': 'Children shouting',
 '/t/dd00136': 'Whimper (dog)',
 '/t/dd00138': 'Brief tone',
 '/t/dd00139': 'Snort (horse)',
 '/t/dd00141': 'Pant (dog)',
 '/t/dd00142': 'Audio logo',
 '/t/dd00143': 'Unknown sound',
 '/t/dd00144': 'Alert',
 '/t/dd00147': 'Dong, bong'}

In [27]:
top_50_mids = my_util.pickle_load("pickle_objects/top_mids/top_50_mids.pckl")
mid_nrs = [30, 35, 40, 45, 50]
write_out_filenames = False
write_out_labels = True

for mid_nr in mid_nrs:

    pckl_name = f"top_{mid_nr}_mids.pckl"
    how_many_mids = str(pckl_name.split("_")[1])
    print(how_many_mids)
    mids = my_util.pickle_load("pickle_objects/top_mids/" + pckl_name)
    print(f"Is mids contained in the top 50 mids: {mids.issubset(top_50_mids)}")

    for table_name in meta_tables:

        split_table_name = table_name.split('_')
        dataset = split_table_name[0]
        datasplit = split_table_name[1]
        meta_table = meta_tables[table_name]

        # Valid filename generation

        filenames = ""
        filenames_name = f"{dataset}_{datasplit}_filenames_top{mid_nr}.txt"
        if dataset == 'audioset':
            filenames = my_util.get_valid_audioset_filenames_for_mids(meta_table, mids)
        else:
            filenames = my_util.get_valid_fsd50k_filenames_for_mids(meta_table, mids)
        print(f"Number of valid files for {dataset} {datasplit}: {len(filenames)}")

        if write_out_filenames:
            my_util.filenames_to_txt(filenames,
                         f"test_filenames/{filenames_name}",
                         dataset=dataset)
        
        # Label generation
        # Sorting by mid count makes it easier to compare between models with a different number of classes
        mids_by_AStrain_counts = my_util.pickle_load(PATH_TO_MIDS_BY_AS_COUNT)
        sorted_mids = sorted(mids, key=lambda x: mids_by_AStrain_counts[x], reverse=True)

        mid_to_multihot_mapping = {}
        multihot_to_mid_mapping = {}
        for idx, mid in enumerate(sorted_mids):
            mid_to_multihot_mapping[mid] = idx
            multihot_to_mid_mapping[idx] = mid
            print(f"{mid} corresponds to multihot label position {idx}")

        # A lot of functionality is behind this, so take a look at utility_funcs.py if needed.
        labels = my_util.get_multihot_labels_per_file(meta_table,
                                                    mids, mid_to_multihot_mapping, dataset=dataset)
        labels_name = f"{dataset}_{datasplit}_labels_{mid_nr}_by_count.pckl"
        if write_out_labels:
            my_util.pickle_save(f"pickle_objects/labels_by_count/{labels_name}", labels)

30
Is mids contained in the top 50 mids: True
Number of valid files for audioset train: 91785
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
Number of valid files for audioset eval: 14976
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
Number of valid files for fsd50k train: 26459
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
Number of valid files for fsd50k eval: 6607
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
35
Is mids contained in the top 50 mids: True
Number of valid files for audioset train: 92340
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
Number of valid files for audioset eval: 15088
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
Number of valid files for fsd50k train: 27309
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
Number of valid files for fsd50k eval: 6851
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
40
Is mids contained in the top 50 mids: True
Number of valid files for audioset train: 92530
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
/m/07r660_ corresponds to multihot label position 35
/m/07rrlb6 corresponds to multihot label position 36
/m/01b_21 corresponds to multihot label position 37
/t/dd00112 corresponds to multihot label position 38
/m/07s0dtb corresponds to multihot label position 39
Number of valid files for audioset eval: 15127
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33
/m/0brhx corresponds to multihot label position 34
/m/07r660_ corresponds to multihot label position 35
/m/07rrlb6 corresponds to multihot label position 36
/m/01b_21 corresponds to multihot label position 37
/t/dd00112 corresponds to multihot label position 38
/m/07s0dtb corresponds to multihot label position 39
Number of valid files for fsd50k train: 28002
/m/05zppz corresponds to multihot label position 0
/m/04rlf corresponds to multihot label position 1
/t/dd00077 corresponds to multihot label position 2
/m/07qjznt corresponds to multihot label position 3
/m/0lyf6 corresponds to multihot label position 4
/m/02zsn corresponds to multihot label position 5
/m/03m9d0z corresponds to multihot label position 6
/m/09l8g corresponds to multihot label position 7
/m/01h8n0 corresponds to multihot label position 8
/m/01j3sz corresponds to multihot label position 9
/m/07qcpgn corresponds to multihot label position 10
/m/020bb7 corresponds to multihot label position 11
/m/0ytgt corresponds to multihot label position 12
/t/dd00003 corresponds to multihot label position 13
/m/07q2z82 corresponds to multihot label position 14
/m/07p6fty corresponds to multihot label position 15
/m/07pbtc8 corresponds to multihot label position 16
/m/03qtwd corresponds to multihot label position 17
/m/07pggtn corresponds to multihot label position 18
/m/0838f corresponds to multihot label position 19
/t/dd00004 corresponds to multihot label position 20
/m/09x0r corresponds to multihot label position 21
/m/0l15bq corresponds to multihot label position 22
/m/012f08 corresponds to multihot label position 23
/m/0k4j corresponds to multihot label position 24
/m/07jdr corresponds to multihot label position 25
/m/0jbk corresponds to multihot label position 26
/m/05tny_ corresponds to multihot label position 27
/m/032s66 corresponds to multihot label position 28
/m/07qnq_y corresponds to multihot label position 29
/m/053hz1 corresponds to multihot label position 30
/m/0bt9lr corresponds to multihot label position 31
/m/0912c9 corresponds to multihot label position 32
/m/0395lw corresponds to multihot label position 33

In [ ]:
# Cross-checking if found number of files based on top X filenames
# equals the number of files found through computed valid filenames list
# Essentially, makes it easy to check that the mid filtering works as intended
audioset_eval_meta_fnames = audioset_eval_meta.copy()
audioset_eval_meta_fnames = audioset_eval_meta_fnames.drop_duplicates()
audioset_eval_meta_fnames = audioset_eval_meta_fnames[audioset_eval_meta_fnames.mids.isin(mids)]
audioset_eval_meta_fnames = set(audioset_eval_meta_fnames['segment_id'])
audioset_eval_meta_fnames = {('_').join(seg.split('_')[0:-1]) for seg in audioset_eval_meta_fnames}
print(len(audioset_eval_meta_fnames))

found_files = 0

PATH_TO_AS_EVAL_AUDIO = r'C:\Users\mp431591\Documents\audioset_eval_files'
with os.scandir(PATH_TO_AS_EVAL_AUDIO) as blob_dir:
    # For each blob
    for idx, entry in enumerate(blob_dir):
        with zf.ZipFile(entry.path, 'r') as archive:
            archive_path = archive.filename

            for zip_info in archive.infolist():

                if zip_info.is_dir():
                    continue
                # Break archive directory structures
                zip_info.filename = os.path.basename(zip_info.filename) 
                filename = zip_info.filename
                clean_file_name = filename.rstrip(".wav")
                clean_file_name_wo_Y = clean_file_name[1::] # remove first character (Y)
                print(clean_file_name_wo_Y)

                if clean_file_name_wo_Y in audioset_eval_meta_fnames:
                    found_files += 1
print(found_files)

In [ ]:
# Here locally available files can be intersected with files with labels, since having the 
# whole dataset available locally is untenable
PATH_TO_LOCAL_AUDIOSET_00_FILES = r'C:\Users\mp431591\Documents\audioset_unbalanced_test\audios\unbalanced_train_segments\unbalanced_train_segments_part00'
test_audioset_files = os.scandir(PATH_TO_LOCAL_AUDIOSET_00_FILES)

for fname in test_audioset_files:
    cleaned_name = ('.').join(fname.name.split('.')[0:-1])[1::]
    if cleaned_name in audioset_train_labels.keys():
        print(cleaned_name)

In [14]:
test_mid_nr = 35
test_mids = my_util.pickle_load(f"pickle_objects/top_mids/top_{test_mid_nr}_mids.pckl")
sorted_mids = sorted(test_mids)

dataset = 'audioset'
datasplit = 'train'
test_file = ''

test_label_dict = my_util.pickle_load(f"C:/Users/mp431591/Documents/work_code/cl_30/continual_learning/pickle_objects/labels/{dataset}_{datasplit}_labels_{test_mid_nr}_dict.pckl")

mid_to_multihot_mapping = {}
multihot_to_mid_mapping = {}
for idx, mid in enumerate(sorted_mids):
    mid_to_multihot_mapping[mid] = idx
    multihot_to_mid_mapping[idx] = mid

#
test_label = [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

test_translation = my_util.multihot_labels_translation(test_label, multihot_to_mid_mapping, as_mid_to_display_dict)
print(test_translation)

['Music', 'Female singing']